"""
GMRI Independent Reproducibility Check
=========================================
Simulates what an independent researcher would do when trying to reproduce
the GMRI on a clean machine.

Does NOT import anything from src/.

Steps:
  1. Load validate/regime_classification.csv — the production reference
     generated by housing_boom_audit.py.
  2. Fetch all five FRED series fresh using fredapi.
  3. Run the full classification pipeline independently:
       cubic spline interpolation, 3-month GDP gap smoothing,
       AND growth logic, 2.5% CPI threshold, 3-month min-duration filter.
  4. Align reproduction series to the same date range as the reference.
  5. Compare month-by-month: count agreements and disagreements.
  6. Compute Cohen's Kappa for inter-rater agreement.
  7. Print PASS if Kappa > 0.95 and all aggregate regime frequencies are
     within ±2pp of the reference, FAIL otherwise with specific details.

Output: validate/reproducibility_check.txt

Run from project root:  python validate/reproducibility_check.py
"""

import os
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd
from dotenv import load_dotenv
from fredapi import Fred

# ---------------------------------------------------------------------------
# Configuration — must match production exactly
# ---------------------------------------------------------------------------
START_DATE    = "1970-01-01"
CPI_THRESHOLD = 2.5
GDP_WINDOW    = 3
MIN_DURATION  = 3
KAPPA_PASS    = 0.95
FREQ_TOL_PP   = 2.0    # ±2pp tolerance for aggregate regime frequencies

REGIME_ORDER = ["Goldilocks", "Overheating", "Stagflation", "Deflationary Bust"]

# ---------------------------------------------------------------------------
# FRED helpers (self-contained — no src/ imports)
# ---------------------------------------------------------------------------

def get_fred_client() -> Fred:
    env_path = Path(__file__).parent.parent / ".env"
    load_dotenv(dotenv_path=env_path)
    api_key = os.environ.get("FRED_API_KEY")
    if not api_key:
        raise ValueError(f"FRED_API_KEY not found. Expected .env at: {env_path}")
    return Fred(api_key=api_key)


def fetch(fred: Fred, series_id: str, start: str) -> pd.Series:
    s = fred.get_series(series_id, observation_start=start).dropna()
    s.name = series_id
    return s


def to_month_end(s: pd.Series) -> pd.Series:
    s = s.copy()
    s.index = s.index + pd.offsets.MonthEnd(0)
    return s


def interp_quarterly(s: pd.Series, method: str = "cubic") -> pd.Series:
    monthly = s.resample("ME").asfreq()
    monthly = monthly.interpolate(method=method)
    return monthly.ffill()


# ---------------------------------------------------------------------------
# Full independent classification pipeline
# ---------------------------------------------------------------------------

def reproduce_regime_series() -> pd.Series:
    """
    Completely independent reproduction of the GMRI regime series.
    Fetches fresh data from FRED and runs the full pipeline from scratch.
    Returns a pd.Series of regime labels indexed by month-end dates.
    """
    fred = get_fred_client()

    # Step 1: Fetch
    print("  Fetching CPIAUCSL...", end=" ", flush=True)
    cpi_raw = to_month_end(fetch(fred, "CPIAUCSL", start=START_DATE))
    print("UNRATE...", end=" ", flush=True)
    unrate  = to_month_end(fetch(fred, "UNRATE",   start=START_DATE))
    print("GDPC1...", end=" ", flush=True)
    gdpc1   = interp_quarterly(to_month_end(fetch(fred, "GDPC1",  start="1947-01-01")), "cubic")
    print("NROU...", end=" ", flush=True)
    nrou    = interp_quarterly(to_month_end(fetch(fred, "NROU",   start="1947-01-01")), "linear")
    print("GDPPOT...")
    gdppot  = interp_quarterly(to_month_end(fetch(fred, "GDPPOT", start="1947-01-01")), "cubic")

    gdpc1.name = "GDPC1"; nrou.name = "NROU"; gdppot.name = "GDPPOT"

    # Step 2: Build CPI YoY
    cpi_yoy = (cpi_raw.pct_change(12) * 100).dropna()
    cpi_yoy.name = "CPI_YOY"

    # Step 3: Align all series
    df = pd.concat([cpi_yoy, unrate, gdpc1, nrou, gdppot], axis=1, join="inner")
    df = df.loc[START_DATE:].dropna()

    # Step 4: GDP gap and smoothing
    gdp_gap        = (df["GDPC1"] - df["GDPPOT"]) / df["GDPPOT"] * 100
    gdp_gap_smooth = gdp_gap.rolling(window=GDP_WINDOW, min_periods=1).mean()
    unemp_gap      = df["UNRATE"] - df["NROU"]

    # Step 5: Growth and inflation signals
    growth_above = (gdp_gap_smooth > 0) & (unemp_gap < 0)
    infl_above   = df["CPI_YOY"] > CPI_THRESHOLD

    # Step 6: Regime assignment
    conditions = [
        growth_above & ~infl_above,
        growth_above &  infl_above,
       ~growth_above &  infl_above,
       ~growth_above & ~infl_above,
    ]
    raw = np.select(conditions, REGIME_ORDER, default="Unknown")
    regime_raw = pd.Series(
        pd.Categorical(raw, categories=REGIME_ORDER),
        index=df.index, name="REGIME",
    )

    # Step 7: Min-duration filter
    filtered = regime_raw.astype(str).copy()
    for _ in range(20):
        block_id = (filtered != filtered.shift()).cumsum()
        changed  = False
        for _bid, group in filtered.groupby(block_id, sort=True):
            if len(group) < MIN_DURATION:
                loc = filtered.index.get_loc(group.index[0])
                if loc > 0:
                    filtered[group.index] = filtered.iloc[loc - 1]
                    changed = True
        if not changed:
            break
    regime = pd.Series(
        pd.Categorical(filtered, categories=REGIME_ORDER),
        index=regime_raw.index, name="REGIME",
    )

    return regime


# ---------------------------------------------------------------------------
# Cohen's Kappa
# ---------------------------------------------------------------------------

def cohen_kappa(y1: pd.Series, y2: pd.Series) -> float:
    """
    Compute Cohen's Kappa for two categorical series over their shared index.
    κ = (P_o − P_e) / (1 − P_e)
    where P_o = observed agreement rate, P_e = expected agreement by chance.
    """
    categories = REGIME_ORDER
    n = len(y1)
    if n == 0:
        return float("nan")

    # Observed agreement
    p_o = (y1.astype(str) == y2.astype(str)).mean()

    # Expected agreement
    p_e = 0.0
    for cat in categories:
        p_e += (y1.astype(str) == cat).mean() * (y2.astype(str) == cat).mean()

    if p_e >= 1.0:
        return 1.0
    return (p_o - p_e) / (1.0 - p_e)


# ---------------------------------------------------------------------------
# Report builder
# ---------------------------------------------------------------------------

def build_report(
    ref: pd.DataFrame,
    repro: pd.Series,
    kappa: float,
    disagreements: pd.DataFrame,
    freq_check: dict,
    pass_kappa: bool,
    pass_freq: bool,
) -> list[str]:
    lines: list[str] = []

    def log(msg: str = "") -> None:
        print(msg)
        lines.append(msg)

    sep  = "=" * 72
    dash = "-" * 72
    overall_pass = pass_kappa and pass_freq

    log(sep)
    log("  GMRI INDEPENDENT REPRODUCIBILITY CHECK")
    log(f"  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    log(sep)
    log()
    log("  Methodology: Independent researcher simulation.")
    log("  No imports from src/. All classification logic re-implemented")
    log("  from scratch in this script. FRED data fetched fresh.")
    log()
    log("  Production reference:  validate/regime_classification.csv")
    log("  Reproduction:          Fresh FRED fetch + independent pipeline")
    log()

    # --- Coverage ---
    log(dash)
    log("  COVERAGE")
    log(dash)
    log()
    log(f"  Production reference:  {len(ref)} months  "
        f"({ref['date'].iloc[0][:7]} – {ref['date'].iloc[-1][:7]})")
    log(f"  Reproduction series:   {len(repro)} months  "
        f"({repro.index[0].strftime('%Y-%m')} – {repro.index[-1].strftime('%Y-%m')})")
    log()

    # Shared date range
    ref_dates   = pd.to_datetime(ref["date"])
    shared_mask = repro.index.isin(ref_dates)
    n_shared    = shared_mask.sum()
    log(f"  Overlapping months:    {n_shared}")
    log()

    # --- Month-by-month agreement ---
    log(dash)
    log("  MONTH-BY-MONTH AGREEMENT")
    log(dash)
    log()

    n_agree    = (len(ref) - len(disagreements))
    n_disagree = len(disagreements)
    agree_rate = n_agree / len(ref) * 100 if len(ref) > 0 else 0.0

    log(f"  Total months compared:   {len(ref)}")
    log(f"  Agreements:              {n_agree}  ({agree_rate:.2f}%)")
    log(f"  Disagreements:           {n_disagree}  ({100-agree_rate:.2f}%)")
    log()

    if n_disagree > 0:
        log(f"  Disagreement detail ({min(n_disagree, 30)} shown):")
        log()
        log(f"  {'Month':<8}  {'Production':<20}  {'Reproduction':<20}")
        log("  " + "-" * 52)
        for _, row in disagreements.head(30).iterrows():
            log(f"  {row['month']:<8}  {row['prod_regime']:<20}  {row['repro_regime']:<20}")
        if n_disagree > 30:
            log(f"  ... and {n_disagree - 30} more")
        log()

        # Disagree regime breakdown
        log("  Disagreement breakdown by (production → reproduction):")
        pair_counts = (
            disagreements.groupby(["prod_regime", "repro_regime"])
            .size()
            .reset_index(name="count")
            .sort_values("count", ascending=False)
        )
        for _, row in pair_counts.iterrows():
            log(f"    {row['prod_regime']:<22} → {row['repro_regime']:<22}  {row['count']} months")
        log()
    else:
        log("  Perfect agreement on all months. ✓")
        log()

    # --- Cohen's Kappa ---
    log(dash)
    log("  COHEN'S KAPPA (inter-rater agreement)")
    log(dash)
    log()
    log(f"  κ = {kappa:.6f}")
    log(f"  Threshold for PASS:  κ > {KAPPA_PASS}")
    if kappa > 0.99:
        kappa_interp = "Near-perfect agreement"
    elif kappa > 0.95:
        kappa_interp = "Almost perfect agreement (above pass threshold)"
    elif kappa > 0.80:
        kappa_interp = "Substantial agreement (below pass threshold)"
    elif kappa > 0.60:
        kappa_interp = "Moderate agreement (below pass threshold)"
    else:
        kappa_interp = "Weak agreement"
    log(f"  Interpretation:      {kappa_interp}")
    kappa_result = "PASS ✓" if pass_kappa else "FAIL ✗"
    log(f"  Result:              {kappa_result}")
    log()

    # --- Aggregate frequency check ---
    log(dash)
    log(f"  AGGREGATE REGIME FREQUENCY CHECK  (tolerance ±{FREQ_TOL_PP}pp)")
    log(dash)
    log()
    log(f"  {'Regime':<22}  {'Prod %':>7}  {'Repro %':>7}  {'Delta':>7}  Result")
    log("  " + "-" * 60)

    freq_pass_all = True
    for r in REGIME_ORDER:
        prod_pct  = freq_check[r]["prod_pct"]
        repro_pct = freq_check[r]["repro_pct"]
        delta     = repro_pct - prod_pct
        within    = abs(delta) <= FREQ_TOL_PP
        if not within:
            freq_pass_all = False
        result = "✓" if within else f"✗  (|{delta:+.2f}pp| > {FREQ_TOL_PP}pp)"
        log(f"  {r:<22}  {prod_pct:>6.2f}%  {repro_pct:>6.2f}%  {delta:>+6.2f}pp  {result}")
    log()
    freq_result = "PASS ✓" if pass_freq else "FAIL ✗"
    log(f"  Frequency check result:  {freq_result}")
    log()

    # --- Overall verdict ---
    log(sep)
    verdict = "PASS" if overall_pass else "FAIL"
    symbol  = "✓" if overall_pass else "✗"
    log(f"  OVERALL RESULT:  {verdict} {symbol}")
    log(sep)
    log()
    if overall_pass:
        log("  The GMRI regime classification is independently reproducible.")
        log("  An external researcher with access to FRED, the published methodology,")
        log(f"  and standard Python libraries achieves κ={kappa:.4f} agreement with")
        log("  the production series — well above the {:.2f} threshold.".format(KAPPA_PASS))
        log("  All regime frequencies are within ±{:.0f}pp of the reference.".format(FREQ_TOL_PP))
    else:
        log("  REPRODUCIBILITY FAILED. Specific divergences:")
        if not pass_kappa:
            log(f"    • Cohen's Kappa = {kappa:.4f} (below {KAPPA_PASS} threshold)")
        if not pass_freq:
            log("    • One or more regime frequencies outside ±{:.0f}pp tolerance".format(FREQ_TOL_PP))
            for r in REGIME_ORDER:
                delta = freq_check[r]["repro_pct"] - freq_check[r]["prod_pct"]
                if abs(delta) > FREQ_TOL_PP:
                    log(f"      {r}: production={freq_check[r]['prod_pct']:.2f}%, "
                        f"reproduction={freq_check[r]['repro_pct']:.2f}%, "
                        f"delta={delta:+.2f}pp")
        log()
        log("  Likely causes of divergence:")
        log("    • FRED data updated between production run and reproduction run")
        log("      (quarterly GDP/NROU/GDPPOT revisions backfill historical data)")
        log("    • Floating-point differences in cubic spline interpolation")
        log("      across different scipy/pandas versions")
        log("    • Min-duration filter edge cases at series boundaries")
    log()
    log(sep)

    return lines


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    print("=" * 60)
    print("  GMRI INDEPENDENT REPRODUCIBILITY CHECK")
    print("=" * 60)

    # Load production reference
    ref_path = Path(__file__).parent / "regime_classification.csv"
    if not ref_path.exists():
        raise FileNotFoundError(
            f"Production reference CSV not found: {ref_path}\n"
            "Run validate/housing_boom_audit.py first to generate it."
        )
    ref = pd.read_csv(ref_path)
    print(f"\nLoaded production reference: {ref_path}")
    print(f"  {len(ref)} months  ({ref['date'].iloc[0][:7]} – {ref['date'].iloc[-1][:7]})")

    # Independent reproduction
    print("\nRunning independent reproduction...")
    repro = reproduce_regime_series()
    print(f"  Reproduction: {len(repro)} months  "
          f"({repro.index[0].strftime('%Y-%m')} – {repro.index[-1].strftime('%Y-%m')})")

    # Align to shared dates
    ref["date_ts"] = pd.to_datetime(ref["date"])
    ref_aligned   = ref.set_index("date_ts")

    # Snap reproduction index to month-end (ref dates are month-start in CSV → convert)
    # ref dates are stored as YYYY-MM-DD (first of month) — convert to month-end for matching
    ref_me_index = ref_aligned.index + pd.offsets.MonthEnd(0)
    ref_aligned.index = ref_me_index

    # Find shared months
    shared = repro.index.intersection(ref_aligned.index)
    n_shared = len(shared)
    print(f"  Shared months: {n_shared}")

    ref_s   = ref_aligned.loc[shared, "REGIME"]
    repro_s = repro.loc[shared].astype(str)
    ref_s_str = ref_s.astype(str)

    # Month-by-month disagreements
    disagree_mask = ref_s_str != repro_s
    disagreements = pd.DataFrame({
        "month":        [d.strftime("%Y-%m") for d in shared[disagree_mask]],
        "prod_regime":  ref_s_str.loc[shared[disagree_mask]].values,
        "repro_regime": repro_s.loc[shared[disagree_mask]].values,
    })

    # Cohen's Kappa
    kappa = cohen_kappa(ref_s_str, repro_s)
    pass_kappa = kappa > KAPPA_PASS

    # Aggregate frequency check
    freq_check = {}
    for r in REGIME_ORDER:
        prod_pct  = (ref_s_str == r).mean() * 100
        repro_pct = (repro_s   == r).mean() * 100
        freq_check[r] = {"prod_pct": prod_pct, "repro_pct": repro_pct}

    pass_freq = all(
        abs(freq_check[r]["repro_pct"] - freq_check[r]["prod_pct"]) <= FREQ_TOL_PP
        for r in REGIME_ORDER
    )

    overall_pass = pass_kappa and pass_freq
    print(f"\n  κ = {kappa:.6f}  ({'PASS' if pass_kappa else 'FAIL'})")
    print(f"  Disagreements: {len(disagreements)}")
    print(f"  Frequency check: {'PASS' if pass_freq else 'FAIL'}")
    print(f"  Overall: {'PASS ✓' if overall_pass else 'FAIL ✗'}")

    # Build report
    print()
    lines = build_report(ref, repro, kappa, disagreements,
                         freq_check, pass_kappa, pass_freq)

    out_path = Path(__file__).parent / "reproducibility_check.txt"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nSaved: {out_path}")


if __name__ == "__main__":
    main()
